version: '3'
services:
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
